def isMasterBranch = env.BRANCH_NAME == "master"
def isDevBranch = env.BRANCH_NAME == "dev"
def isfixBranch = env.BRANCH_NAME == "fix"

pipeline{
    agent any{
        stages{
            stage('Build'){
                tools {
                    maven 'Maven-3.8'
                } 
                buildDefinitionFile = "pom.xml"
            }
            
            stage('Publish') {
                executeCreateArtifact = true
                executePublishArtifact = (isMasterBranch || isDevBranch)
                artifactoryRepo = "**/target/*.war"
                publishMode = "FILE_SPEC"
                }
            }

            stage('Test'){
                steps{
                    sh 'mvn test'
                }
            }
        }
    }
}